import React, { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { motion } from "framer-motion";


/**
 * Supabase setup
 * 1) npm install @supabase/supabase-js
 * 2) Add these environment variables in Vercel / .env.local:
 *    VITE_SUPABASE_URL=your_supabase_project_url
 *    VITE_SUPABASE_ANON_KEY=your_supabase_anon_key
 *
 * 3) Create the table using this SQL in Supabase SQL Editor:
 *
 * create table if not exists public.projects (
 *   id bigint generated by default as identity primary key,
 *   title text not null,
 *   creator text not null default '익명 메이커',
 *   tag text not null default '첫 배포',
 *   tool text not null default '',
 *   build_time text not null default '',
 *   description text not null,
 *   lesson text not null default '',
 *   project_link text,
 *   likes integer not null default 0,
 *   comments integer not null default 0,
 *   created_at timestamptz not null default now()
 * );
 *
 * alter table public.projects enable row level security;
 *
 * create policy "Anyone can read projects"
 * on public.projects
 * for select
 * using (true);
 *
 * create policy "Anyone can insert projects"
 * on public.projects
 * for insert
 * with check (true);
 */

const supabaseUrl = import.meta.env?.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;

const demoProjects = [
  {
    id: 1,
    title: "군인 휴가 계산기",
    creator: "비전공 대학생",
    tag: "첫 배포",
    tool: "ChatGPT + Replit",
    build_time: "3시간",
    description: "복잡한 휴가 일정을 입력하면 남은 휴가와 복귀 날짜를 자동으로 계산해주는 작은 웹앱.",
    lesson: "처음엔 배포가 제일 무서웠는데, 링크가 생기니까 진짜 만든 느낌이 들었다.",
    project_link: "",
    likes: 128,
    comments: 18,
  },
  {
    id: 2,
    title: "외국인용 한국 여행 플래너",
    creator: "관광 아이디어 보유자",
    tag: "아이디어 실험",
    tool: "Claude + Cursor",
    build_time: "5시간",
    description: "여행 목적과 예산을 넣으면 외국인에게 맞는 한국 여행 코스를 추천하는 MVP.",
    lesson: "완벽한 서비스보다 먼저 보여주는 게 더 중요하다는 걸 배웠다.",
    project_link: "",
    likes: 214,
    comments: 33,
  },
  {
    id: 3,
    title: "카페 예약 페이지",
    creator: "알바생 메이커",
    tag: "비개발자 제작",
    tool: "Lovable + ChatGPT",
    build_time: "2시간",
    description: "동네 카페에서 간단히 예약을 받을 수 있는 페이지. 메뉴, 시간, 연락처 입력까지 가능.",
    lesson: "코드를 몰라도 내가 불편했던 걸 직접 해결할 수 있다는 게 충격이었다.",
    project_link: "",
    likes: 97,
    comments: 11,
  },
];

const principles = [
  {
    icon: "🚀",
    title: "실행이 먼저",
    body: "완성도보다 첫 시도, 첫 배포, 첫 공유를 더 크게 인정합니다.",
  },
  {
    icon: "👥",
    title: "비개발자 중심",
    body: "GitHub 감성이 아니라, 아이디어를 가진 평범한 청년들이 편하게 올리는 공간입니다.",
  },
  {
    icon: "🛡️",
    title: "훈수보다 응원",
    body: "스택 논쟁, 코드 비판보다 제작 과정과 용기를 존중하는 문화를 만듭니다.",
  },
];

const steps = [
  "아이디어를 떠올린다",
  "GPT, Claude, Cursor 등으로 만들어본다",
  "결과물과 제작 과정을 올린다",
  "서로 피드백하고 rating 한다",
  "첫 사용자와 첫 개선을 경험한다",
];

const emptyForm = {
  title: "",
  creator: "",
  tag: "첫 배포",
  tool: "",
  build_time: "",
  description: "",
  lesson: "",
  project_link: "",
};

function normalizeProject(project) {
  return {
    id: project.id,
    title: project.title ?? "제목 없는 프로젝트",
    creator: project.creator ?? "익명 메이커",
    tag: project.tag ?? "첫 배포",
    tool: project.tool ?? "",
    build_time: project.build_time ?? project.time ?? "",
    description: project.description ?? project.desc ?? "",
    lesson: project.lesson ?? "",
    project_link: project.project_link ?? "",
    likes: project.likes ?? 0,
    comments: project.comments ?? 0,
  };
}

function filterProjects(projectList, query, filter) {
  return projectList.filter((project) => {
    const normalizedQuery = query.trim().toLowerCase();
    const searchSource = `${project.title} ${project.description} ${project.tool} ${project.creator}`.toLowerCase();
    const matchesQuery = normalizedQuery.length === 0 || searchSource.includes(normalizedQuery);
    const matchesFilter = filter === "전체" || project.tag === filter;
    return matchesQuery && matchesFilter;
  });
}

function validateProjectInput(input) {
  const errors = {};

  if (!input.title.trim()) errors.title = "프로젝트 제목을 입력해주세요.";
  if (!input.description.trim()) errors.description = "프로젝트 설명을 입력해주세요.";
  if (input.project_link.trim()) {
    try {
      new URL(input.project_link.trim());
    } catch {
      errors.project_link = "링크는 https:// 로 시작하는 올바른 URL이어야 합니다.";
    }
  }

  return errors;
}

function runSelfTests() {
  const normalizedDemoProjects = demoProjects.map(normalizeProject);
  const tests = [
    {
      name: "전체 필터는 모든 프로젝트를 반환한다",
      actual: filterProjects(normalizedDemoProjects, "", "전체").length,
      expected: 3,
    },
    {
      name: "태그 필터는 해당 태그만 반환한다",
      actual: filterProjects(normalizedDemoProjects, "", "첫 배포").map((project) => project.title).join(","),
      expected: "군인 휴가 계산기",
    },
    {
      name: "검색어는 제목, 설명, 툴, 제작자에서 동작한다",
      actual: filterProjects(normalizedDemoProjects, "Claude", "전체").map((project) => project.title).join(","),
      expected: "외국인용 한국 여행 플래너",
    },
    {
      name: "검색어와 태그 필터를 함께 적용한다",
      actual: filterProjects(normalizedDemoProjects, "ChatGPT", "비개발자 제작").map((project) => project.title).join(","),
      expected: "카페 예약 페이지",
    },
    {
      name: "필수값 누락 시 validation error를 반환한다",
      actual: Object.keys(validateProjectInput({ ...emptyForm, title: "", description: "" })).join(","),
      expected: "title,description",
    },
    {
      name: "잘못된 URL은 validation error를 반환한다",
      actual: validateProjectInput({ ...emptyForm, title: "테스트", description: "설명", project_link: "not-a-url" }).project_link,
      expected: "링크는 https:// 로 시작하는 올바른 URL이어야 합니다.",
    },
  ];

  const failed = tests.filter((test) => test.actual !== test.expected);
  if (failed.length > 0) {
    console.error("Self tests failed:", failed);
  }
}

runSelfTests();

function Button({ children, className = "", ...props }) {
  return (
    <button
      className={`rounded-2xl bg-black px-5 py-3 text-white transition hover:opacity-90 ${className}`}
      {...props}
    >
      {children}
    </button>
  );
}

function Card({ children, className = "" }) {
  return (
    <div
      className={`rounded-[2rem] border border-neutral-200 bg-white shadow-sm ${className}`}
    >
      {children}
    </div>
  );
}

function CardContent({ children, className = "" }) {
  return <div className={className}>{children}</div>;
}

function IconBadge({ children, className = "" }) {
  return (
    <span
      className={`inline-flex h-10 w-10 items-center justify-center rounded-2xl bg-neutral-100 text-lg ${className}`}
      aria-hidden="true"
    >
      {children}
    </span>
  );
}

function SmallIcon({ children }) {
  return (
    <span className="inline-flex h-5 w-5 items-center justify-center text-sm" aria-hidden="true">
      {children}
    </span>
  );
}

export default function VibeMakerCommunityWebMvp() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("전체");
  const [projects, setProjects] = useState(demoProjects.map(normalizeProject));
  const [form, setForm] = useState(emptyForm);
  const [errors, setErrors] = useState({});
  const [isLoading, setIsLoading] = useState(Boolean(supabase));
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [statusMessage, setStatusMessage] = useState(
    supabase ? "Supabase DB에 연결 중입니다." : "현재는 데모 모드입니다. Supabase 환경변수를 넣으면 실제 DB에 저장됩니다."
  );

  useEffect(() => {
    async function loadProjects() {
      if (!supabase) return;

      setIsLoading(true);
      const { data, error } = await supabase
        .from("projects")
        .select("id,title,creator,tag,tool,build_time,description,lesson,project_link,likes,comments,created_at")
        .order("created_at", { ascending: false });

      if (error) {
        console.error(error);
        setStatusMessage("DB에서 프로젝트를 불러오지 못해 데모 데이터를 표시합니다. Supabase 테이블과 RLS 정책을 확인해주세요.");
        setProjects(demoProjects.map(normalizeProject));
      } else {
        setProjects((data ?? []).map(normalizeProject));
        setStatusMessage("Supabase DB와 연결되었습니다. 등록하면 친구들도 같은 피드에서 볼 수 있습니다.");
      }

      setIsLoading(false);
    }

    loadProjects();
  }, []);

  const filteredProjects = useMemo(() => {
    return filterProjects(projects, query, filter);
  }, [projects, query, filter]);

  const heroStats = useMemo(() => {
    const creatorCount = new Set(projects.map((project) => project.creator)).size;
    return [
      [`${projects.length}+`, "등록 프로젝트"],
      [`${creatorCount}+`, "첫 제작자"],
      [supabase ? "DB" : "DEMO", supabase ? "공유 가능" : "데모 모드"],
    ];
  }, [projects]);

  function handleFormChange(field, value) {
    setForm((previous) => ({ ...previous, [field]: value }));
    setErrors((previous) => ({ ...previous, [field]: undefined }));
  }

  async function handleSubmit(event) {
    event.preventDefault();

    const nextErrors = validateProjectInput(form);
    if (Object.keys(nextErrors).length > 0) {
      setErrors(nextErrors);
      setStatusMessage("필수 입력값을 확인해주세요.");
      return;
    }

    const payload = {
      title: form.title.trim(),
      creator: form.creator.trim() || "익명 메이커",
      tag: form.tag,
      tool: form.tool.trim(),
      build_time: form.build_time.trim(),
      description: form.description.trim(),
      lesson: form.lesson.trim(),
      project_link: form.project_link.trim() || null,
    };

    setIsSubmitting(true);

    if (!supabase) {
      const demoProject = normalizeProject({
        ...payload,
        id: Date.now(),
        likes: 0,
        comments: 0,
      });
      setProjects((previous) => [demoProject, ...previous]);
      setForm(emptyForm);
      setStatusMessage("데모 모드라 현재 브라우저에서만 추가되었습니다. Supabase를 연결하면 친구들도 볼 수 있습니다.");
      setIsSubmitting(false);
      return;
    }

    const { data, error } = await supabase
      .from("projects")
      .insert(payload)
      .select("id,title,creator,tag,tool,build_time,description,lesson,project_link,likes,comments,created_at")
      .single();

    if (error) {
      console.error(error);
      setStatusMessage("등록에 실패했습니다. Supabase insert policy와 테이블 컬럼을 확인해주세요.");
    } else {
      setProjects((previous) => [normalizeProject(data), ...previous]);
      setForm(emptyForm);
      setStatusMessage("등록되었습니다. 이제 같은 웹에 접속한 친구들도 볼 수 있습니다.");
      window.location.hash = "projects";
    }

    setIsSubmitting(false);
  }

  return (
    <div className="min-h-screen bg-neutral-50 text-neutral-950">
      <header className="sticky top-0 z-30 border-b border-neutral-200 bg-white/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
          <div className="flex items-center gap-2">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-neutral-950 text-white shadow-sm">
              ✨
            </div>
            <div>
              <p className="text-lg font-bold tracking-tight">첫배포</p>
              <p className="text-xs text-neutral-500">Korean AI Maker Community</p>
            </div>
          </div>
          <nav className="hidden items-center gap-6 text-sm text-neutral-600 md:flex">
            <a href="#projects" className="hover:text-neutral-950">프로젝트</a>
            <a href="#culture" className="hover:text-neutral-950">문화</a>
            <a href="#upload" className="hover:text-neutral-950">올리기</a>
          </nav>
          <a href="#upload">
            <Button className="rounded-2xl px-5">프로젝트 올리기</Button>
          </a>
        </div>
      </header>

      <main>
        <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-[1.1fr_0.9fr] md:py-24">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.55 }}
            className="flex flex-col justify-center"
          >
            <div className="mb-5 inline-flex w-fit items-center gap-2 rounded-full border border-neutral-200 bg-white px-4 py-2 text-sm text-neutral-700 shadow-sm">
              <SmallIcon>🪄</SmallIcon>
              비개발자도 아이디어를 세상에 배포하는 시대
            </div>
            <h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-7xl">
              생각만 하던 아이디어를,
              <span className="block text-neutral-500">직접 만들고 공개하는 공간.</span>
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-neutral-600">
              첫배포는 한국 청년들이 GPT, Claude, Cursor 같은 AI 도구로 만든 앱과 서비스를 올리고, 제작 과정을 공유하고, 서로 rating 하는 실행 중심 커뮤니티입니다.
            </p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <a href="#upload">
                <Button size="lg" className="w-full rounded-2xl px-7 sm:w-auto">
                  첫 프로젝트 올리기
                </Button>
              </a>
              <a href="#projects">
                <Button size="lg" variant="outline" className="w-full rounded-2xl px-7 sm:w-auto">
                  다른 사람의 첫 배포 보기
                </Button>
              </a>
            </div>
            <div className="mt-8 grid max-w-xl grid-cols-3 gap-3 text-center">
              {heroStats.map(([num, label]) => (
                <div key={label} className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm">
                  <p className="text-2xl font-black">{num}</p>
                  <p className="mt-1 text-xs text-neutral-500">{label}</p>
                </div>
              ))}
            </div>
            <p className="mt-4 max-w-xl text-sm leading-6 text-neutral-500">{statusMessage}</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.55, delay: 0.1 }}
            className="relative"
          >
            <div className="absolute -right-4 -top-4 h-40 w-40 rounded-full bg-neutral-200 blur-3xl" />
            <Card className="relative overflow-hidden rounded-[2rem] border-neutral-200 bg-white shadow-xl">
              <CardContent className="p-5">
                <div className="rounded-3xl bg-neutral-950 p-5 text-white">
                  <div className="flex items-center justify-between">
                    <p className="font-semibold">오늘의 첫 배포</p>
                    <span aria-hidden="true">⭐</span>
                  </div>
                  <h3 className="mt-8 text-3xl font-black">알바 스케줄 자동 생성기</h3>
                  <p className="mt-3 text-sm leading-6 text-neutral-300">
                    “매주 바뀌는 알바 스케줄 짜기가 귀찮아서 AI로 만들어봤어요. 개발은 처음입니다.”
                  </p>
                </div>
                <div className="mt-4 grid grid-cols-2 gap-3">
                  <div className="rounded-3xl bg-neutral-100 p-4">
                    <SmallIcon>⏱️</SmallIcon>
                    <p className="mt-3 text-sm text-neutral-500">제작 시간</p>
                    <p className="font-bold">4시간</p>
                  </div>
                  <div className="rounded-3xl bg-neutral-100 p-4">
                    <SmallIcon>✨</SmallIcon>
                    <p className="mt-3 text-sm text-neutral-500">사용한 AI</p>
                    <p className="font-bold">Claude</p>
                  </div>
                </div>
                <div className="mt-4 rounded-3xl border border-neutral-200 p-4">
                  <p className="text-sm font-semibold">제작자의 한마디</p>
                  <p className="mt-2 text-sm leading-6 text-neutral-600">
                    “처음엔 내가 이런 걸 올려도 되나 싶었는데, 누군가 댓글로 써보고 싶다고 해서 계속 개선하고 있어요.”
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </section>

        <section id="culture" className="border-y border-neutral-200 bg-white py-14">
          <div className="mx-auto max-w-7xl px-5">
            <div className="max-w-2xl">
              <p className="text-sm font-bold text-neutral-500">WHY THIS EXISTS</p>
              <h2 className="mt-3 text-3xl font-black tracking-tight md:text-5xl">
                한국 청년들에게 필요한 건 더 많은 공부가 아니라, 작은 실행 경험입니다.
              </h2>
            </div>
            <div className="mt-10 grid gap-4 md:grid-cols-3">
              {principles.map(({ icon, title, body }) => (
                <Card key={title} className="rounded-3xl border-neutral-200 shadow-sm">
                  <CardContent className="p-6">
                    <IconBadge>{icon}</IconBadge>
                    <h3 className="mt-5 text-xl font-black">{title}</h3>
                    <p className="mt-3 leading-7 text-neutral-600">{body}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-7xl px-5 pt-10 md:pt-16">
          <div className="rounded-[2rem] border border-neutral-200 bg-gradient-to-br from-neutral-950 to-neutral-800 p-6 text-white shadow-xl md:p-10">
            <div className="grid gap-8 md:grid-cols-[0.95fr_1.05fr] md:items-center">
              <div>
                <p className="text-sm font-bold uppercase tracking-[0.2em] text-neutral-400">
                  FOUNDING MAKERS
                </p>
                <h2 className="mt-4 text-3xl font-black tracking-tight md:text-5xl">
                  첫 시작은 우리끼리 만든 것부터.
                </h2>
                <p className="mt-5 max-w-xl leading-8 text-neutral-300">
                  아직 거대한 플랫폼이 아니어도 괜찮습니다. 지금은 한국 청년들이 “나도 뭔가 만들어볼 수 있다”는 분위기를 만드는 단계입니다. 처음에는 내가 만든 것, 친구가 만든 것, 작은 아이디어들을 서로 올리며 시작합니다.
                </p>
                <div className="mt-8 flex flex-wrap gap-3 text-sm">
                  {[
                    "첫 프로젝트 공유",
                    "친구와 같이 제작",
                    "실패 사례 환영",
                    "비전공자 중심",
                  ].map((item) => (
                    <span
                      key={item}
                      className="rounded-full border border-white/15 bg-white/10 px-4 py-2 text-neutral-200 backdrop-blur"
                    >
                      {item}
                    </span>
                  ))}
                </div>
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                {[
                  {
                    title: "학교 팀플 도우미",
                    creator: "컴공 아닌 친구 2명",
                    desc: "GPT로 회의록 정리와 역할 분배 기능을 붙여본 첫 웹앱.",
                    emoji: "📚",
                  },
                  {
                    title: "데이트 코스 추천기",
                    creator: "디자인 전공 친구",
                    desc: "서울 지역 기반으로 분위기 좋은 코스를 추천하는 작은 서비스.",
                    emoji: "💌",
                  },
                  {
                    title: "군대 준비 체크리스트",
                    creator: "입대 예정 대학생",
                    desc: "입대 전에 필요한 준비물을 AI로 정리하고 저장하는 앱.",
                    emoji: "🎖️",
                  },
                  {
                    title: "카페 재고 기록기",
                    creator: "카페 알바생",
                    desc: "매일 종이에 쓰던 재고 체크를 모바일로 바꿔본 첫 프로젝트.",
                    emoji: "☕",
                  },
                ].map((item) => (
                  <div
                    key={item.title}
                    className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur"
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-2xl">
                        {item.emoji}
                      </div>
                      <span className="rounded-full bg-white/10 px-3 py-1 text-xs text-neutral-300">
                        초기 메이커
                      </span>
                    </div>
                    <h3 className="mt-5 text-xl font-black tracking-tight">
                      {item.title}
                    </h3>
                    <p className="mt-2 text-sm text-neutral-400">
                      {item.creator}
                    </p>
                    <p className="mt-4 text-sm leading-7 text-neutral-200">
                      {item.desc}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section id="projects" className="mx-auto max-w-7xl px-5 py-16">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end">
            <div>
              <p className="text-sm font-bold text-neutral-500">PROJECT FEED</p>
              <h2 className="mt-3 text-3xl font-black tracking-tight md:text-5xl">사람들이 지금 만든 것들</h2>
              <p className="mt-4 max-w-2xl text-neutral-600">
                코드를 잘 짰는지보다, 왜 만들었고 어디까지 해봤는지가 더 중요합니다.
              </p>
            </div>
            <div className="flex flex-col gap-3 sm:flex-row">
              <div className="flex items-center gap-2 rounded-2xl border border-neutral-200 bg-white px-4 py-3 shadow-sm">
                <SmallIcon>🔎</SmallIcon>
                <input
                  value={query}
                  onChange={(event) => setQuery(event.target.value)}
                  placeholder="프로젝트 검색"
                  className="w-48 bg-transparent text-sm outline-none"
                />
              </div>
              <div className="flex items-center gap-2 rounded-2xl border border-neutral-200 bg-white px-4 py-3 shadow-sm">
                <SmallIcon>⚙️</SmallIcon>
                <select
                  value={filter}
                  onChange={(event) => setFilter(event.target.value)}
                  className="bg-transparent text-sm outline-none"
                >
                  <option>전체</option>
                  <option>첫 배포</option>
                  <option>아이디어 실험</option>
                  <option>비개발자 제작</option>
                </select>
              </div>
            </div>
          </div>

          {isLoading ? (
            <div className="mt-10 rounded-3xl border border-neutral-200 bg-white p-8 text-center text-neutral-500 shadow-sm">
              프로젝트를 불러오는 중입니다.
            </div>
          ) : filteredProjects.length === 0 ? (
            <div className="mt-10 rounded-3xl border border-neutral-200 bg-white p-8 text-center text-neutral-500 shadow-sm">
              아직 조건에 맞는 프로젝트가 없습니다. 첫 프로젝트를 올려보세요.
            </div>
          ) : (
            <div className="mt-10 grid gap-5 md:grid-cols-3">
              {filteredProjects.map((project) => (
                <motion.article
                  key={project.id}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.35 }}
                >
                  <Card className="h-full overflow-hidden rounded-[2rem] border-neutral-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl">
                    <CardContent className="flex h-full flex-col p-0">
                      <div className="h-44 bg-gradient-to-br from-neutral-100 to-neutral-300 p-5">
                        <span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-neutral-700 shadow-sm">
                          {project.tag}
                        </span>
                      </div>
                      <div className="flex flex-1 flex-col p-6">
                        <div className="flex items-start justify-between gap-4">
                          <h3 className="text-2xl font-black tracking-tight">{project.title}</h3>
                          {project.project_link ? (
                            <a
                              href={project.project_link}
                              target="_blank"
                              rel="noreferrer"
                              className="mt-1 text-neutral-400 hover:text-neutral-950"
                              aria-label={`${project.title} 열기`}
                            >
                              ↗
                            </a>
                          ) : (
                            <span className="mt-1 text-neutral-300" aria-hidden="true">↗</span>
                          )}
                        </div>
                        <p className="mt-2 text-sm text-neutral-500">{project.creator}</p>
                        <p className="mt-4 leading-7 text-neutral-700">{project.description}</p>
                        <div className="mt-5 grid grid-cols-2 gap-3 text-sm">
                          <div className="rounded-2xl bg-neutral-100 p-3">
                            <p className="text-neutral-500">사용 툴</p>
                            <p className="mt-1 font-bold">{project.tool || "미입력"}</p>
                          </div>
                          <div className="rounded-2xl bg-neutral-100 p-3">
                            <p className="text-neutral-500">제작 시간</p>
                            <p className="mt-1 font-bold">{project.build_time || "미입력"}</p>
                          </div>
                        </div>
                        {project.lesson ? (
                          <div className="mt-5 rounded-2xl border border-neutral-200 p-4">
                            <p className="text-xs font-bold text-neutral-500">배운 점</p>
                            <p className="mt-2 text-sm leading-6 text-neutral-700">{project.lesson}</p>
                          </div>
                        ) : null}
                        <div className="mt-auto flex items-center gap-4 pt-5 text-sm text-neutral-500">
                          <span className="flex items-center gap-1">♡ {project.likes}</span>
                          <span className="flex items-center gap-1">💬 {project.comments}</span>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </motion.article>
              ))}
            </div>
          )}
        </section>

        <section className="bg-neutral-950 py-16 text-white">
          <div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-[0.85fr_1.15fr] md:items-center">
            <div>
              <p className="text-sm font-bold text-neutral-400">HOW IT WORKS</p>
              <h2 className="mt-3 text-3xl font-black tracking-tight md:text-5xl">이곳은 개발자 평가장이 아니라 실행 인증장입니다.</h2>
              <p className="mt-5 leading-8 text-neutral-300">
                첫배포의 목표는 더 좋은 AI를 만드는 것이 아니라, 이미 존재하는 AI 도구를 이용해 한국 청년들이 자기 아이디어를 실제 결과물로 공개하게 만드는 것입니다.
              </p>
            </div>
            <div className="grid gap-3">
              {steps.map((step, index) => (
                <div key={step} className="flex items-center gap-4 rounded-3xl bg-white/10 p-5 backdrop-blur">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-white text-sm font-black text-neutral-950">
                    {index + 1}
                  </div>
                  <p className="font-semibold">{step}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section id="upload" className="mx-auto max-w-7xl px-5 py-16">
          <form onSubmit={handleSubmit} className="grid gap-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:grid-cols-[0.9fr_1.1fr] md:p-10">
            <div>
              <div className="mb-5 flex h-14 w-14 items-center justify-center rounded-3xl bg-neutral-950 text-white">
                ⬆️
              </div>
              <h2 className="text-3xl font-black tracking-tight md:text-5xl">너의 첫 프로젝트를 올려봐.</h2>
              <p className="mt-5 leading-8 text-neutral-600">
                완벽하지 않아도 됩니다. 작은 아이디어, 어설픈 결과물, 실패한 시도도 누군가에게는 시작할 용기가 됩니다.
              </p>
              <div className="mt-6 rounded-3xl bg-neutral-100 p-5 text-sm leading-7 text-neutral-600">
                <p className="font-bold text-neutral-900">현재 저장 방식</p>
                <p className="mt-2">
                  {supabase
                    ? "Supabase DB에 저장됩니다. 같은 웹에 접속한 사람들도 새 프로젝트를 볼 수 있습니다."
                    : "아직 Supabase 환경변수가 없어 데모 모드입니다. 입력한 내용은 현재 화면에만 추가됩니다."}
                </p>
              </div>
            </div>
            <div className="grid gap-4">
              <div>
                <label className="sr-only" htmlFor="project-title">프로젝트 제목</label>
                <input
                  id="project-title"
                  value={form.title}
                  onChange={(event) => handleFormChange("title", event.target.value)}
                  className="w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  placeholder="프로젝트 제목 *"
                />
                {errors.title ? <p className="mt-2 text-sm text-red-600">{errors.title}</p> : null}
              </div>

              <div>
                <label className="sr-only" htmlFor="project-creator">제작자</label>
                <input
                  id="project-creator"
                  value={form.creator}
                  onChange={(event) => handleFormChange("creator", event.target.value)}
                  className="w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  placeholder="제작자 이름 또는 닉네임"
                />
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <label className="sr-only" htmlFor="project-tag">카테고리</label>
                  <select
                    id="project-tag"
                    value={form.tag}
                    onChange={(event) => handleFormChange("tag", event.target.value)}
                    className="w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  >
                    <option>첫 배포</option>
                    <option>아이디어 실험</option>
                    <option>비개발자 제작</option>
                  </select>
                </div>
                <div>
                  <label className="sr-only" htmlFor="build-time">제작 시간</label>
                  <input
                    id="build-time"
                    value={form.build_time}
                    onChange={(event) => handleFormChange("build_time", event.target.value)}
                    className="w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                    placeholder="제작 시간"
                  />
                </div>
              </div>

              <div>
                <label className="sr-only" htmlFor="ai-tool">사용한 AI 툴</label>
                <input
                  id="ai-tool"
                  value={form.tool}
                  onChange={(event) => handleFormChange("tool", event.target.value)}
                  className="w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  placeholder="사용한 AI 툴"
                />
              </div>

              <div>
                <label className="sr-only" htmlFor="project-description">프로젝트 설명</label>
                <textarea
                  id="project-description"
                  value={form.description}
                  onChange={(event) => handleFormChange("description", event.target.value)}
                  className="min-h-28 w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  placeholder="왜 만들었고, 어떤 문제를 해결하려 했나요? *"
                />
                {errors.description ? <p className="mt-2 text-sm text-red-600">{errors.description}</p> : null}
              </div>

              <div>
                <label className="sr-only" htmlFor="project-lesson">배운 점</label>
                <textarea
                  id="project-lesson"
                  value={form.lesson}
                  onChange={(event) => handleFormChange("lesson", event.target.value)}
                  className="min-h-24 w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  placeholder="만들면서 배운 점, 막혔던 점, 느낀 점"
                />
              </div>

              <div>
                <label className="sr-only" htmlFor="project-link">서비스 링크 또는 데모 링크</label>
                <input
                  id="project-link"
                  value={form.project_link}
                  onChange={(event) => handleFormChange("project_link", event.target.value)}
                  className="w-full rounded-2xl border border-neutral-200 px-4 py-4 outline-none focus:border-neutral-950"
                  placeholder="서비스 링크 또는 데모 링크"
                />
                {errors.project_link ? <p className="mt-2 text-sm text-red-600">{errors.project_link}</p> : null}
              </div>

              <Button size="lg" type="submit" disabled={isSubmitting} className="rounded-2xl py-6 text-base">
                {isSubmitting ? "등록 중..." : "첫 배포 등록하기"}
              </Button>
            </div>
          </form>
        </section>
      </main>

      <footer className="border-t border-neutral-200 bg-white py-8">
        <div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 text-sm text-neutral-500 md:flex-row">
          <p>© 첫배포 — 한국 청년 AI 메이커 커뮤니티</p>
          <p>공부만 하던 아이디어를, 직접 세상에 공개하는 문화.</p>
        </div>
      </footer>
    </div>
  );
}
